// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Wallet struct {
	ID      string `json:"id"`
	Balance int32  `json:"balance"`
}
