// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sql

import (
	"time"

	"github.com/google/uuid"
)

type Wallet struct {
	ID         uuid.UUID
	Balance    int32
	CreateDate time.Time
	UpdateDate time.Time
}
